### ISSUE TITLE
Snapshot Collector may not be able to find ShadowCopyFolder in .NET 6 single file executables

### ISSUE THREAD

**Issue by somehowadev** [microsoft/ApplicationInsights-SnapshotCollector#21]
Observed this exception when trying to use snapshot collector (v1.4.3) with a program published as a single binary.

Event: ExceptionDuringNativeComponentExtraction

System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path) 
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized) at

Can't get too much detail given the environment contraints but I'll see if I can get more info if needed.

**Comment by pharring** [comment]
Sorry for the delayed response. Yes, this looks like a bug. We haven't tested that scenario. I'll log a corresponding internal work item to track it.

**Comment by pharring** [comment]
I tracked down the bug and have a fix in review. Once it's merged, I'll publish a new nuget version. Should be available next week.

**Comment by pharring** [comment]
Fix is in the 1.4.4-pre release.
@somehowadev please try https://www.nuget.org/packages/Microsoft.ApplicationInsights.SnapshotCollector/1.4.4-pre-2304.2302

**Comment by pharring** [comment]
1.4.4 (stable) is out now. [Release notes](https://learn.microsoft.com/azure/azure-monitor/snapshot-debugger/snapshot-debugger#144).
